const companies = require('./companies/companies.service.js');
const branches = require('./branches/branches.service.js');
const departments = require('./departments/departments.service.js');
const sections = require('./sections/sections.service.js');
const roles = require('./roles/roles.service.js');
const positions = require('./positions/positions.service.js');
const templates = require('./templates/templates.service.js');
const mails = require('./mails/mails.service.js');
const tests = require('./tests/tests.service.js');
const userAddresses = require('./userAddresses/userAddresses.service.js');
const companyAddresses = require('./companyAddresses/companyAddresses.service.js');
const companyPhones = require('./companyPhones/companyPhones.service.js');
const users = require('./users/users.service.js');
const userPhones = require('./userPhones/userPhones.service.js');
const userInvites = require('./userInvites/userInvites1.service.js');
const staffinfo = require('./staffinfo/staffinfo.service.js');
const profiles = require('./profiles/profiles.service.js');
// 280624
const permissionServices = require('./permissionServices/permissionServices.service.js');
const permissionFields = require('./permissionFields/permissionFields.service.js');
const dynaLoader = require('./dynaLoader/dynaLoader.service.js');
const dynaFields = require('./dynaFields/dynaFields.service.js');
const mailQues = require('./mailQues/mailQues.service.js');
const employees = require('./employees/employees.service.js');
const jobQues = require('./jobQues/jobQues.service.js');
const superior = require('./superior/superior.service.js');
const prompts = require('./prompts/prompts.service.js');
const config = require('./config/config.service.js');
const chatai = require('./chatai/chatai.service.js');

const departmentAdmin = require('./departmentAdmin/departmentAdmin.service.js');
const departmentHOD = require('./departmentHOD/departmentHOD.service.js');
const departmentHOS = require('./departmentHOS/departmentHOS.service.js');
const mailWH = require('./mailWH/mailWH.service.js');
const inbox = require('./inbox/inbox.service.js');
const notifications = require('./notifications/notifications.service.js');
const errors = require('./errors/errors.service.js');
const errorsWH = require('./errorsWH/errorsWH.service.js');
const userLogin = require('./userLogin/userLogin1.service.js');
const cbRefPackages = require("./cbRefPackages/cbRefPackages.service.js");
const cbRefHosting = require("./cbRefHosting/cbRefHosting.service.js");
const cbRefSupport = require("./cbRefSupport/cbRefSupport.service.js");
const cbRefDomains = require("./cbRefDomains/cbRefDomains.service.js");
const cbRefDiscountCode = require("./cbRefDiscountCode/cbRefDiscountCode.service.js");
const cbRefGitPrivate = require("./cbRefGitPrivate/cbRefGitPrivate.service.js");
const addonDiscount = require("./addonDiscount/addonDiscount.service.js");
const addonPackage = require("./addonPackage/addonPackage.service.js");
const addonHosting = require("./addonHosting/addonHosting.service.js");
const addonDomain = require("./addonDomain/addonDomain.service.js");
const addonPrivacy = require("./addonPrivacy/addonPrivacy.service.js");
const addonUsers = require("./addonUsers/addonUsers.service.js");
const projects = require("./projects/projects.service.js");
const addonSupport = require("./addonSupport/addonSupport.service.js");
// ~cb-add-require-service-name~

// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
    app.configure(users);
    app.configure(companies);
    app.configure(branches);
    app.configure(departments);
    app.configure(sections);
    app.configure(roles);
    app.configure(positions);
    app.configure(profiles);
    app.configure(templates);
    app.configure(mails);
    app.configure(tests);
    app.configure(permissionServices);
    app.configure(permissionFields);
    app.configure(userAddresses);
    app.configure(companyAddresses);
    app.configure(companyPhones);
    app.configure(userPhones);
    app.configure(userInvites);
    app.configure(staffinfo);
    app.configure(dynaLoader);
    app.configure(dynaFields);
    app.configure(mailQues);
    app.configure(employees);
    app.configure(jobQues);
    app.configure(superior);
    // gen ai
    app.configure(prompts);
    app.configure(config);
    app.configure(chatai);

    app.configure(departmentAdmin);
    app.configure(departmentHOD);
    app.configure(departmentHOS);
    app.configure(mailWH);
    app.configure(inbox);
    app.configure(notifications);
    app.configure(errors);
    app.configure(errorsWH);
    app.configure(userLogin);
  app.configure(cbRefPackages);
  app.configure(cbRefHosting);
  app.configure(cbRefSupport);
  app.configure(cbRefDomains);
  app.configure(cbRefDiscountCode);
  app.configure(cbRefGitPrivate);
  app.configure(addonDiscount);
  app.configure(addonPackage);
  app.configure(addonHosting);
  app.configure(addonDomain);
  app.configure(addonPrivacy);
  app.configure(addonUsers);
  app.configure(projects);
  app.configure(addonSupport);
    // ~cb-add-configure-service-name~
};
